version: "3.8"

services:
  appserver:
    user: root
    container_name: appserver
    build: .
    depends_on:
      - mysqlserver
      - redisserver
      - emailserver
    command: ["bin/wait-for-it.sh mysqlserver:3306 -t 120 && jboss-eap-7.2/bin/standalone.sh"]
    ports:
      - "8080:8080"
      #- "9990:9990"
      #- "8787:8787"
    environment:
      TZ: "America/Sao_Paulo"
      JBOSS_USER: "root"
      BRANCH: ${BRANCH:-master}
    volumes:
      - log-volume:/var/log
      - tmp-volume:/var/tmp/siga
    networks:
      - siga

  mysqlserver:
    container_name: mysqlserver
    image: mysql:8.0.21
    restart: always
    expose:
      - "3306"
    ports:
      - 5001:3306
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: "siga"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - siga
    #   - mysql-volume:/var/lib/mysql

  redisserver:
    container_name: redisserver
    command: redis-server --requirepass ***REPLACE-WITH-RANDOM-GUID***
    image: redis:alpine
    expose:
      - "6379"
    ports:
      - 5002:6379
    networks:
      - siga
  
  emailserver:
    container_name: emailserver
    image: schickling/mailcatcher
    restart: always
    expose:
      - "1080"
      - "1045"
    ports:
      - 5003:1080
      - 5004:1025
    networks:
      - siga

volumes:
  log-volume: {}
  tmp-volume: {}
  mysql-volume: {}

networks:
  siga:
